version: "3.7"
services:
  frigate:
    container_name: frigate
    hostname: frigate
    image: blakeblackshear/frigate:0.12.0-beta2-tensorrt
    privileged: true
    shm_size: "256mb"    
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /storage/docker/frigate/config.yml:/config/config.yml:ro
      - /storage/docker/frigate/storage:/media/frigate
      - /storage/docker/frigate/trt-models:/trt-models
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "127.0.0.1:9049:5000"
    environment:
      FRIGATE_RTSP_PASSWORD: "somepassword"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,video
    restart: unless-stopped
